# Generated by Django 5.0.6 on 2024-07-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=111, null=True)),
                ('num', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
