# Generated by Django 5.0.6 on 2024-07-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_priz_alter_skills_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_details')),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('project_date', models.CharField(blank=True, max_length=100, null=True)),
                ('project_url', models.URLField()),
                ('about_project', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='priz',
            name='n',
            field=models.URLField(blank=True, null=True),
        ),
    ]
