# Generated by Django 5.0.6 on 2024-08-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_portfolio_portfolio_details_priz_n'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio_details',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='image_main',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='about_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_details',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_details'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(default='None'),
            preserve_default=False,
        ),
    ]
