# Generated by Django 5.1 on 2024-08-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_delete_portfolio_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.TextField(blank=True, max_length=150, null=True)),
                ('recent_post', models.CharField(blank=True, max_length=150, null=True)),
                ('archives', models.CharField(blank=True, max_length=150, null=True)),
                ('tags', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
