# Generated by Django 5.1 on 2024-08-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_blog_blogsingle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-08-23 06:01:42.934978+00'),
            preserve_default=False,
        ),
    ]
